### ISSUE TITLE
Langzamer pannen/zoomen naar een wijk/locatie

### ISSUE THREAD

**Issue by rinzeb** [TNOCS/wodk#44]
Met ipv zonder animatie

**Comment by erikvullings** [comment]
Suggestie: als je van A naar B wil gaan, zoom dan eerst uit naar een punt C halverwege A en B, zodanig dat A en B beide in beeld zijn, en vandaar zoom in naar B. Dan verlies je niet je context.

**Comment by rinzeb** [comment]
Heb de flyTo() functie van leaflet 1.0 gebruikt, vervangt de panTo() : http://leafletjs.com/2015/07/15/leaflet-1.0-beta1-released.html
