### ISSUE TITLE
Stap terug, vooruit, refresh functionaliteit

### ISSUE THREAD

**Issue by rinzeb** [TNOCS/wodk#45]
Afvangen van die 3 events van de browser (en evt dummy functie aanroepen).

**Comment by erikvullings** [comment]
http://stackoverflow.com/questions/22247294/how-do-i-get-the-back-button-to-work-with-an-angularjs-ui-router-state-machine

Dus je moet urls genereren voor je stappen...

**Comment by erikvullings** [comment]
Voor nu houden we het even op de buttons
